### ISSUE TITLE
升级 0.1.7 后 get_sim() 输入句子有问题

### ISSUE THREAD

**Issue by love1017best** [shibing624/text2vec#21]
File "~\test\venv\lib\site-packages\gensim\models\keyedvectors.py", line 396, in get_index
    raise KeyError(f"Key '{key}' not present")
KeyError: "Key '未读' not present"

调用的方法是 Similarity().get_score(句子, 词语)
输入的句子是：'1. 合理利用学生的初始阅读背景。例如教师在封面环节请未读本书学生回答'
输入的词语随意
感觉好像是句子经过分词以后，遇到没有词向量的词，就无法运行了
尝试换用 0.1.6 版配合 gensim 3.8.3 在这种情况下是可以输出结果的，0.1.7 配合 4.0.0 就不可以了

**Comment by shibing624** [comment]
fix with 0.1.8发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming ***@***.***>发送时间: 2021年5月6日 17:25收件人: shibing624/text2vec ***@***.***>抄送: Subscribed ***@***.***>主题: 回复：[shibing624/text2vec] 升级 0.1.7 后 get_sim() 输入句子有问题 (#21)
File "~\test\venv\lib\site-packages\gensim\models\keyedvectors.py", line 396, in get_index
raise KeyError(f"Key '{key}' not present")
KeyError: "Key '未读' not present"
调用的方法是 Similarity().get_score(句子, 词语)
感觉好像是句子经过分词以后，遇到没有词向量的词，就无法运行了
尝试换用 0.1.6 版配合 getsim 3.8.3 在这种情况下是可以输出结果的，0.1.7 配合 4.0.0 就不可以了

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/shibing624/text2vec/issues/21",
"url": "https://github.com/shibing624/text2vec/issues/21",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shibing624** [comment]
fix with https://github.com/shibing624/text2vec/commit/e0912b4e2b9238300ca43a0b9c83278317dc9a05
