### ISSUE TITLE
'Word2VecKeyedVectors' object has no attribute 'key_to_index'

### ISSUE THREAD

**Issue by songdejia** [shibing624/text2vec#23]
Hi, how to fix  'Word2VecKeyedVectors' object has no attribute 'key_to_index' after loading xxx.bin file in w2v = KeyedVectors.load_word2vec_format(self.w2v_path, **self.w2v_kwargs)

**Comment by shibing624** [comment]
update gensim发自我的iPhone------------------ Original ------------------From: chendeming ***@***.***>Date: Wed,May 26,2021 8:13 PMTo: shibing624/text2vec ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [shibing624/text2vec] 'Word2VecKeyedVectors' object has no attribute'key_to_index' (#23)
Hi, how to fix  'Word2VecKeyedVectors' object has no attribute 'key_to_index' after loading xxx.bin file in w2v = KeyedVectors.load_word2vec_format(self.w2v_path, **self.w2v_kwargs)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/shibing624/text2vec/issues/23",
"url": "https://github.com/shibing624/text2vec/issues/23",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shibing624** [comment]
更新gensim到4.0.0版本
