### ISSUE TITLE
腾讯词向量官方全量的链接点击404

### ISSUE THREAD

**Issue by hhhhjjj** [shibing624/text2vec#30]
https://ai.tencent.com/ailab/nlp/data/Tencent_AILab_ChineseEmbedding.tar.gz

**Comment by shibing624** [comment]
fixed发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming ***@***.***>发送时间: 2021年11月5日 13:58收件人: shibing624/text2vec ***@***.***>抄送: Subscribed ***@***.***>主题: 回复：[shibing624/text2vec] 腾讯词向量官方全量的链接点击404 (Issue #30)
https://ai.tencent.com/ailab/nlp/data/Tencent_AILab_ChineseEmbedding.tar.gz

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/shibing624/text2vec/issues/30",
"url": "https://github.com/shibing624/text2vec/issues/30",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shibing624** [comment]
http://42.193.145.218/light_Tencent_AILab_ChineseEmbedding.bin 从这里也能拿到。

**Comment by shibing624** [comment]
https://ai.tencent.com/ailab/nlp/zh/download.html
