### ISSUE TITLE
怎么在使用text2vec.Similarity的时候调用GPU？

### ISSUE THREAD

**Issue by Fan-Jian-Zheng** [shibing624/text2vec#39]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import text2vec; text2vec.__version__`.

**Comment by Fan-Jian-Zheng** [comment]
您的工作真的给了我很多的帮助，但是在实际使用的时候还是效率太低了，有考虑写一个在调用模型的时候使用GPU的接口么？

**Comment by shibing624** [comment]
默认是GPU，机器支持gpu就会调用cuda:0的。

**Comment by shibing624** [comment]
默认就是gpu吧发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming ***@***.***>发送时间: 2022年4月8日 15:14收件人: shibing624/text2vec ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [shibing624/text2vec] 怎么在使用text2vec.Similarity的时候调用GPU？ (Issue #39)
Describe the Question
Please provide a clear and concise description of what the question is.
Describe your attempts

 I walked through the tutorials
 I checked the documentation
 I checked to make sure that this is not a duplicate question

You may also provide a Minimal, Complete, and Verifiable example you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).
In addition, figure out your version by running import text2vec; text2vec.__version__.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/shibing624/text2vec/issues/39",
"url": "https://github.com/shibing624/text2vec/issues/39",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
